model:
  arch: resnet101
  pretrained: True
  emb_dim: 512
  maxpool: 1
  out_activation: linear
  activation: relu

training:
  optimizer:
    lr: 0.0001

data:
  training:
    batch_size: 5096
  testing:
    batch_size: 8192
